# MySQL. Versions 5.5.8 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: r4r
  password: USER_PASS
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: classical_music_shop_development

test:
  <<: *default
  database: classical_music_shop_test

production:
  <<: *default
  database: classical_music_shop_production
  username: classical_music_shop
  password: <%= ENV['CLASSICAL_MUSIC_SHOP_DATABASE_PASSWORD'] %>
